name: Run Vulture Dead Code Detection
description: Find unused code with vulture and push results to Loki

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  path:
    description: 'Path to analyze'
    required: false
    default: 'src'
  min_confidence:
    description: 'Minimum confidence level (0-100)'
    required: false
    default: '80'
  exclude:
    description: 'Patterns to exclude (comma-separated)'
    required: false
    default: ''
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  status:
    description: 'Analysis status (passed/failed)'
    value: ${{ steps.analyze.outputs.status }}
  dead_code_items:
    description: 'Number of dead code items found'
    value: ${{ steps.analyze.outputs.dead_code_items }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install vulture
      shell: bash
      run: |
        uv pip install vulture

    - name: Run vulture
      id: analyze
      shell: bash
      continue-on-error: true
      run: |
        EXCLUDE_ARGS=""
        if [ -n "${{ inputs.exclude }}" ]; then
          IFS=',' read -ra PATTERNS <<< "${{ inputs.exclude }}"
          for pattern in "${PATTERNS[@]}"; do
            EXCLUDE_ARGS="$EXCLUDE_ARGS --exclude $pattern"
          done
        fi

        uv run vulture ${{ inputs.path }} \
          --min-confidence ${{ inputs.min_confidence }} \
          $EXCLUDE_ARGS > vulture_output.txt 2>&1
        VULTURE_EXIT_CODE=$?

        # Count dead code items
        DEAD_CODE=$(grep -c "unused" vulture_output.txt || echo "0")
        echo "dead_code_items=$DEAD_CODE" >> $GITHUB_OUTPUT

        if [ $DEAD_CODE -eq 0 ]; then
          echo "status=passed" >> $GITHUB_OUTPUT
          echo "No dead code found!"
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "Found $DEAD_CODE dead code items:"
          cat vulture_output.txt
        fi

        exit $VULTURE_EXIT_CODE

    - name: Upload vulture results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: vulture-dead-code-report
        path: vulture_output.txt
        retention-days: 7

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.analyze.outputs.status }}
        extra_labels: '{"check_type": "dead_code", "dead_code_items": "${{ steps.analyze.outputs.dead_code_items }}"}'
        message: "Vulture dead code analysis ${{ steps.analyze.outputs.status }}, ${{ steps.analyze.outputs.dead_code_items }} items found"

    - name: Fail if dead code found
      shell: bash
      if: steps.analyze.outputs.status == 'failed'
      run: exit 1
