name: Build Documentation
description: Build documentation with Sphinx or MkDocs and push results to Loki

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  docs_tool:
    description: 'Documentation tool (sphinx or mkdocs)'
    required: false
    default: 'sphinx'
  docs_dir:
    description: 'Documentation directory'
    required: false
    default: 'docs'
  output_dir:
    description: 'Output directory for built docs'
    required: false
    default: 'docs/_build/html'
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  status:
    description: 'Build status (passed/failed)'
    value: ${{ steps.build.outputs.status }}
  warnings:
    description: 'Number of warnings during build'
    value: ${{ steps.build.outputs.warnings }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: |
        uv sync

    - name: Build Sphinx documentation
      if: inputs.docs_tool == 'sphinx'
      id: build-sphinx
      shell: bash
      continue-on-error: true
      run: |
        cd ${{ inputs.docs_dir }}
        uv run sphinx-build -W -b html . ${{ inputs.output_dir }} > ../docs_build.log 2>&1
        BUILD_EXIT_CODE=$?

        WARNINGS=$(grep -c "WARNING" ../docs_build.log || echo "0")
        echo "warnings=$WARNINGS" >> $GITHUB_OUTPUT

        if [ $BUILD_EXIT_CODE -eq 0 ]; then
          echo "status=passed" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          cat ../docs_build.log
        fi
        exit $BUILD_EXIT_CODE

    - name: Build MkDocs documentation
      if: inputs.docs_tool == 'mkdocs'
      id: build-mkdocs
      shell: bash
      continue-on-error: true
      run: |
        uv run mkdocs build --strict > docs_build.log 2>&1
        BUILD_EXIT_CODE=$?

        WARNINGS=$(grep -c "WARNING" docs_build.log || echo "0")
        echo "warnings=$WARNINGS" >> $GITHUB_OUTPUT

        if [ $BUILD_EXIT_CODE -eq 0 ]; then
          echo "status=passed" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          cat docs_build.log
        fi
        exit $BUILD_EXIT_CODE

    - name: Set build status
      id: build
      shell: bash
      run: |
        if [ "${{ inputs.docs_tool }}" = "sphinx" ]; then
          echo "status=${{ steps.build-sphinx.outputs.status }}" >> $GITHUB_OUTPUT
          echo "warnings=${{ steps.build-sphinx.outputs.warnings }}" >> $GITHUB_OUTPUT
        else
          echo "status=${{ steps.build-mkdocs.outputs.status }}" >> $GITHUB_OUTPUT
          echo "warnings=${{ steps.build-mkdocs.outputs.warnings }}" >> $GITHUB_OUTPUT
        fi

    - name: Upload documentation
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ${{ inputs.output_dir }}
        retention-days: 7

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.build.outputs.status }}
        extra_labels: '{"build_type": "documentation", "docs_tool": "${{ inputs.docs_tool }}", "warnings": "${{ steps.build.outputs.warnings }}"}'
        message: "Documentation build ${{ steps.build.outputs.status }} using ${{ inputs.docs_tool }}, ${{ steps.build.outputs.warnings }} warnings"

    - name: Fail if build failed
      shell: bash
      if: steps.build.outputs.status == 'failed'
      run: exit 1
