name: Secret Scanning
description: Scan for accidentally committed secrets using gitleaks and push results to Loki

inputs:
  config_path:
    description: 'Path to gitleaks config file (optional)'
    required: false
    default: ''
  scan_path:
    description: 'Path to scan (default: entire repo)'
    required: false
    default: '.'
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  status:
    description: 'Scan status (passed/failed)'
    value: ${{ steps.scan.outputs.status }}
  secrets_found:
    description: 'Number of secrets found'
    value: ${{ steps.scan.outputs.secrets_found }}

runs:
  using: composite
  steps:
    - name: Run Gitleaks
      id: scan
      shell: bash
      continue-on-error: true
      run: |
        # Install gitleaks
        wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz
        tar -xzf gitleaks_8.18.1_linux_x64.tar.gz
        chmod +x gitleaks

        # Run scan
        CONFIG_ARG=""
        if [ -n "${{ inputs.config_path }}" ]; then
          CONFIG_ARG="--config=${{ inputs.config_path }}"
        fi

        ./gitleaks detect $CONFIG_ARG --source=${{ inputs.scan_path }} --report-format=json --report-path=gitleaks-report.json --no-git || true
        SCAN_EXIT_CODE=$?

        # Parse results
        if [ -f gitleaks-report.json ]; then
          SECRETS=$(jq '. | length' gitleaks-report.json)
          echo "secrets_found=$SECRETS" >> $GITHUB_OUTPUT

          if [ "$SECRETS" -eq 0 ]; then
            echo "status=passed" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "status=failed" >> $GITHUB_OUTPUT
            echo "Found $SECRETS potential secrets"
            jq -r '.[] | "File: \(.File), Line: \(.StartLine), Secret: \(.Secret)"' gitleaks-report.json
            exit 1
          fi
        else
          echo "secrets_found=0" >> $GITHUB_OUTPUT
          echo "status=passed" >> $GITHUB_OUTPUT
        fi

    - name: Upload gitleaks results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-secret-scan
        path: gitleaks-report.json
        retention-days: 30

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.scan.outputs.status }}
        extra_labels: '{"security_tool": "gitleaks", "secrets_found": "${{ steps.scan.outputs.secrets_found }}"}'
        message: "Secret scan ${{ steps.scan.outputs.status }}, ${{ steps.scan.outputs.secrets_found }} secrets found"

    - name: Fail if secrets found
      shell: bash
      if: steps.scan.outputs.status == 'failed'
      run: exit 1
