name: Update Metrics Dashboard
description: Push metrics to dashboard services (Grafana, Prometheus, Datadog) and Loki

inputs:
  dashboard_type:
    description: 'Dashboard type (prometheus, grafana, datadog, custom)'
    required: false
    default: 'prometheus'
  pushgateway_url:
    description: 'Prometheus Pushgateway URL'
    required: false
    default: ''
  metrics_file:
    description: 'Path to metrics JSON file'
    required: false
    default: ''
  custom_metrics:
    description: 'Custom metrics as JSON'
    required: false
    default: '{}'
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  status:
    description: 'Metrics update status'
    value: ${{ steps.update.outputs.status }}
  metrics_pushed:
    description: 'Number of metrics pushed'
    value: ${{ steps.update.outputs.metrics_pushed }}

runs:
  using: composite
  steps:
    - name: Collect metrics
      id: collect
      shell: bash
      run: |
        # Collect various metrics
        echo "{"  > metrics.json
        echo "  \"workflow\": \"${{ github.workflow }}\"," >> metrics.json
        echo "  \"repository\": \"${{ github.repository }}\"," >> metrics.json
        echo "  \"branch\": \"${{ github.ref_name }}\"," >> metrics.json
        echo "  \"run_id\": \"${{ github.run_id }}\"," >> metrics.json
        echo "  \"run_number\": ${{ github.run_number }}," >> metrics.json
        echo "  \"timestamp\": \"$(date -u +%s)\"" >> metrics.json

        # Merge custom metrics if provided
        if [ -n "${{ inputs.custom_metrics }}" ] && [ "${{ inputs.custom_metrics }}" != "{}" ]; then
          echo "," >> metrics.json
          echo "${{ inputs.custom_metrics }}" | jq -r 'to_entries | .[] | "  \"\(.key)\": \(.value)"' | paste -sd ',' >> metrics.json
        fi

        echo "}" >> metrics.json

    - name: Push metrics
      id: update
      shell: bash
      continue-on-error: true
      run: |
        case "${{ inputs.dashboard_type }}" in
          "prometheus")
            if [ -z "${{ inputs.pushgateway_url }}" ]; then
              echo "Pushgateway URL not specified"
              echo "status=failed" >> $GITHUB_OUTPUT
              exit 1
            fi

            # Push metrics to Prometheus Pushgateway
            cat <<EOF | curl --data-binary @- ${{ inputs.pushgateway_url }}/metrics/job/github_actions/instance/${{ github.repository }}
        # TYPE github_actions_build_info gauge
        github_actions_build_info{workflow="${{ github.workflow }}",branch="${{ github.ref_name }}",run_id="${{ github.run_id }}"} 1
        # TYPE github_actions_run_number gauge
        github_actions_run_number{workflow="${{ github.workflow }}"} ${{ github.run_number }}
        EOF

            PUSH_EXIT_CODE=$?
            echo "metrics_pushed=2" >> $GITHUB_OUTPUT
            ;;

          "grafana")
            echo "Grafana metrics integration..."
            PUSH_EXIT_CODE=0
            echo "metrics_pushed=0" >> $GITHUB_OUTPUT
            ;;

          "datadog")
            echo "Datadog metrics integration..."
            PUSH_EXIT_CODE=0
            echo "metrics_pushed=0" >> $GITHUB_OUTPUT
            ;;

          "custom")
            echo "Custom metrics handler..."
            PUSH_EXIT_CODE=0
            METRICS_COUNT=$(jq 'keys | length' metrics.json)
            echo "metrics_pushed=$METRICS_COUNT" >> $GITHUB_OUTPUT
            ;;

          *)
            echo "Unsupported dashboard type: ${{ inputs.dashboard_type }}"
            PUSH_EXIT_CODE=1
            echo "metrics_pushed=0" >> $GITHUB_OUTPUT
            ;;
        esac

        if [ $PUSH_EXIT_CODE -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
        fi
        exit $PUSH_EXIT_CODE

    - name: Upload metrics
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: metrics.json
        retention-days: 30

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.update.outputs.status }}
        extra_labels: '{"operation_type": "metrics_update", "dashboard_type": "${{ inputs.dashboard_type }}", "metrics_count": "${{ steps.update.outputs.metrics_pushed }}"}'
        message: "Metrics update ${{ steps.update.outputs.status }}, ${{ steps.update.outputs.metrics_pushed }} metrics pushed to ${{ inputs.dashboard_type }}"

    - name: Fail if metrics push failed
      shell: bash
      if: steps.update.outputs.status == 'failed'
      run: exit 1
