name: License Checker
description: Check dependency licenses and push results to Loki

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  allowed_licenses:
    description: 'Comma-separated list of allowed licenses (empty = allow all)'
    required: false
    default: ''
  forbidden_licenses:
    description: 'Comma-separated list of forbidden licenses'
    required: false
    default: 'GPL-3.0,AGPL-3.0'
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  status:
    description: 'License check status (passed/failed)'
    value: ${{ steps.check.outputs.status }}
  violations:
    description: 'Number of license violations'
    value: ${{ steps.check.outputs.violations }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: |
        uv sync
        uv pip install pip-licenses

    - name: Check licenses
      id: check
      shell: bash
      continue-on-error: true
      run: |
        uv run pip-licenses --format=json > licenses.json
        uv run pip-licenses --format=plain > licenses.txt

        VIOLATIONS=0
        FORBIDDEN="${{ inputs.forbidden_licenses }}"

        if [ -n "$FORBIDDEN" ]; then
          IFS=',' read -ra FORBIDDEN_ARRAY <<< "$FORBIDDEN"
          for license in "${FORBIDDEN_ARRAY[@]}"; do
            COUNT=$(grep -c "$license" licenses.txt || echo "0")
            VIOLATIONS=$((VIOLATIONS + COUNT))
          done
        fi

        echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT

        if [ $VIOLATIONS -eq 0 ]; then
          echo "status=passed" >> $GITHUB_OUTPUT
          echo "All dependency licenses are compliant"
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "Found $VIOLATIONS license violations:"
          cat licenses.txt
        fi

        [ $VIOLATIONS -eq 0 ]

    - name: Upload license report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: license-report
        path: |
          licenses.json
          licenses.txt
        retention-days: 30

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.check.outputs.status }}
        extra_labels: '{"check_type": "license", "violations": "${{ steps.check.outputs.violations }}"}'
        message: "License check ${{ steps.check.outputs.status }}, ${{ steps.check.outputs.violations }} violations found"

    - name: Fail if violations found
      shell: bash
      if: steps.check.outputs.status == 'failed'
      run: exit 1
