name: Semantic Release
description: Run semantic-release to create a new release and push results to Loki

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  github_token:
    description: 'GitHub token for semantic-release'
    required: true
  pypi_token:
    description: 'PyPI token for publishing (optional)'
    required: false
    default: ''
  build_command:
    description: 'Build command to run before publishing'
    required: false
    default: 'uv build'
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  version:
    description: 'New version that was released'
    value: ${{ steps.release.outputs.version }}
  status:
    description: 'Release status (success/failed/no-release)'
    value: ${{ steps.release.outputs.status }}
  released:
    description: 'Whether a new release was created'
    value: ${{ steps.release.outputs.released }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install semantic-release
      shell: bash
      run: |
        uv pip install python-semantic-release

    - name: Build package
      shell: bash
      if: inputs.build_command != ''
      run: |
        ${{ inputs.build_command }}

    - name: Run semantic release
      id: release
      shell: bash
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        # Run semantic release
        uv run semantic-release version > semantic_release_output.txt 2>&1
        RELEASE_EXIT_CODE=$?

        # Check if a release was created
        if grep -q "No release will be made" semantic_release_output.txt; then
          echo "status=no-release" >> $GITHUB_OUTPUT
          echo "released=false" >> $GITHUB_OUTPUT
          echo "version=" >> $GITHUB_OUTPUT
        elif [ $RELEASE_EXIT_CODE -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "released=true" >> $GITHUB_OUTPUT
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "unknown")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "released=false" >> $GITHUB_OUTPUT
          echo "version=" >> $GITHUB_OUTPUT
          cat semantic_release_output.txt
        fi
        exit $RELEASE_EXIT_CODE

    - name: Publish to PyPI
      if: steps.release.outputs.released == 'true' && inputs.pypi_token != ''
      shell: bash
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ inputs.pypi_token }}
      run: |
        uv pip install twine
        uv run twine upload dist/*

    - name: Create release summary
      if: always()
      shell: bash
      run: |
        echo "### Semantic Release Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ steps.release.outputs.status }}" >> $GITHUB_STEP_SUMMARY
        echo "**Released:** ${{ steps.release.outputs.released }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.release.outputs.released }}" = "true" ]; then
          echo "**Version:** \`${{ steps.release.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.release.outputs.status }}
        extra_labels: '{"release_type": "semantic_release", "version": "${{ steps.release.outputs.version }}", "released": "${{ steps.release.outputs.released }}"}'
        message: "Semantic release ${{ steps.release.outputs.status }}, version: ${{ steps.release.outputs.version }}, released: ${{ steps.release.outputs.released }}"

    - name: Fail if release failed
      shell: bash
      if: steps.release.outputs.status == 'failed'
      run: exit 1
