name: Integration Tests
description: Run integration tests and push results to Loki

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  test_path:
    description: 'Path to integration tests'
    required: false
    default: 'tests/integration'
  pytest_args:
    description: 'Additional pytest arguments'
    required: false
    default: '-v'
  services:
    description: 'Services to start (comma-separated, e.g., postgres,redis)'
    required: false
    default: ''
  loki_url:
    description: 'Loki endpoint URL'
    required: true
  loki_user:
    description: 'Loki username for basic auth'
    required: false
    default: ''
  loki_password:
    description: 'Loki password for basic auth'
    required: false
    default: ''

outputs:
  status:
    description: 'Test status (passed/failed)'
    value: ${{ steps.test.outputs.status }}
  tests_passed:
    description: 'Number of tests passed'
    value: ${{ steps.test.outputs.tests_passed }}
  tests_failed:
    description: 'Number of tests failed'
    value: ${{ steps.test.outputs.tests_failed }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: |
        uv sync

    - name: Run integration tests
      id: test
      shell: bash
      continue-on-error: true
      run: |
        uv run pytest ${{ inputs.test_path }} ${{ inputs.pytest_args }} \
          --junitxml=integration-test-results.xml \
          --json-report --json-report-file=integration-test-report.json
        TEST_EXIT_CODE=$?

        # Parse results
        if [ -f integration-test-report.json ]; then
          PASSED=$(jq '.summary.passed // 0' integration-test-report.json)
          FAILED=$(jq '.summary.failed // 0' integration-test-report.json)
          echo "tests_passed=$PASSED" >> $GITHUB_OUTPUT
          echo "tests_failed=$FAILED" >> $GITHUB_OUTPUT
        else
          echo "tests_passed=0" >> $GITHUB_OUTPUT
          echo "tests_failed=0" >> $GITHUB_OUTPUT
        fi

        if [ $TEST_EXIT_CODE -eq 0 ]; then
          echo "status=passed" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
        fi
        exit $TEST_EXIT_CODE

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          integration-test-results.xml
          integration-test-report.json
        retention-days: 7

    - name: Push results to Loki
      if: always()
      uses: ./.github/actions/push-to-loki
      with:
        loki_url: ${{ inputs.loki_url }}
        loki_user: ${{ inputs.loki_user }}
        loki_password: ${{ inputs.loki_password }}
        job_status: ${{ steps.test.outputs.status }}
        extra_labels: '{"test_type": "integration", "passed": "${{ steps.test.outputs.tests_passed }}", "failed": "${{ steps.test.outputs.tests_failed }}"}'
        message: "Integration tests ${{ steps.test.outputs.status }}, ${{ steps.test.outputs.tests_passed }} passed, ${{ steps.test.outputs.tests_failed }} failed"

    - name: Fail if tests failed
      shell: bash
      if: steps.test.outputs.status == 'failed'
      run: exit 1
